namespace LinuxInfo.Enumerators.DefaultFileDefinitions {
    public static class Etc {
        /// <summary>
        /// GPT 4 Maintained.
        /// </summary>
        public static Dictionary<string, string> DefaultConfigurables = new() {
            { "/etc/passwd", "Contains user account information." },
            { "/etc/shadow", "Secure storage for passwords." },
            { "/etc/group", "Group account information." },
            { "/etc/gshadow", "Secure storage for group passwords." },
            { "/etc/fstab", "File system mount points." },
            { "/etc/hostname", "System's network name." },
            { "/etc/hosts", "Local hostname to IP address mappings." },
            { "/etc/networks", "Network name information." },
            { "/etc/nsswitch.conf", "Name service switch configuration." },
            { "/etc/resolv.conf", "Resolver configuration for DNS." },
            { "/etc/services", "Service name and port number mappings." },
            { "/etc/protocols", "Protocol names and numbers." },
            { "/etc/crontab", "Schedule of automated tasks." },
            { "/etc/init.d", "Initialization scripts for services." },
            { "/etc/systemd", "Configuration files for systemd, if the system uses systemd." },
            { "/etc/skel", "Template files for new user home directories." },
            { "/etc/bashrc", "System-wide configuration for Bash shell." },
            { "/etc/profile", "System-wide initialization script for shell sessions." },
            { "/etc/sysctl.conf", "Kernel parameter settings." },
            { "/etc/rc.local", "Script executed at the end of each multiuser runlevel." },
            { "/etc/apt/sources.list", "Repository sources for APT (Debian/Ubuntu)." },
            { "/etc/yum.conf", "Configuration for YUM package manager (CentOS/RHEL)." },
            { "/etc/ssh/sshd_config", "Configuration for SSH server." },
            { "/etc/sudoers", "Permissions for sudo." },
            { "/etc/environment", "System-wide environment variables." },
            { "/etc/logrotate.conf", "Configuration for log file rotation." },
            { "/etc/mailname", "The internet hostname of the mail system (on some systems)." },
            { "/etc/motd", "Message of the Day, displayed after login." },
            { "/etc/aliases", "Used for mail aliases in mail servers." },
            { "/etc/issue", "System identification text displayed before the login prompt." },
            { "/etc/issue.net", "System identification text for remote logins." },
            { "/etc/sysconfig", "Scripts and configuration files for system startup." },
            { "/etc/cups", "Configuration files for CUPS (Common UNIX Printing System)." },
            { "/etc/default", "Default configuration files for various applications and services." },
            { "/etc/X11", "Configuration files for the X Window System." },
            { "/etc/exports", "Configuration for NFS (Network File System) exports." },
            { "/etc/ldap", "Configuration files for LDAP (Lightweight Directory Access Protocol) services." },
            { "/etc/pam.d", "Configuration files for PAM (Pluggable Authentication Modules)." },
            { "/etc/rsyslog.conf", "Configuration file for system logging with rsyslog." },
            { "/etc/syslog.conf", "Configuration file for system logging with syslog." },
            { "/etc/security", "Security-related configurations, often for PAM modules." },
            { "/etc/ssl/certs", "Directory for SSL/TLS certificates." },
            { "/etc/ssl/private", "Directory for SSL/TLS private keys." },
            { "/etc/timezone", "File containing the system's timezone." },
            { "/etc/udev", "Configuration files for udev, the device manager for the Linux kernel." },
            { "/etc/inittab", "Controls the initialization of the system for init process." },
            { "/etc/modules", "Lists kernel modules to load at boot time." },
            { "/etc/modprobe.d", "Configuration files for modprobe." },
            { "/etc/sysconfig/network", "Network configuration settings on some systems." },
            { "/etc/rc.d", "Startup and shutdown scripts in some Unix-like systems." },
            { "/etc/ld.so.conf", "Configuration for the dynamic linker run-time bindings." },
            { "/etc/ld.so.conf.d", "Additional dynamic linker run-time bindings." },
            { "/etc/locale.conf", "System-wide locale settings." },
            { "/etc/locale.gen", "Specifies locales to be generated." },
            { "/etc/machine-id", "Contains a unique ID of the machine." },
            { "/etc/os-release", "Operating system identification data." },
            { "/etc/profile.d", "Additional shell scripts run by /etc/profile." },
            { "/etc/securetty", "Lists terminals where root login is allowed." },
            { "/etc/shells", "Lists valid login shells." },
            { "/etc/inputrc", "Global configuration for GNU Readline." },
            { "/etc/adjtime", "Records information about clock adjustments." },
            { "/etc/cron.d", "Directory for cron jobs defined by the user." },
            { "/etc/cron.daily", "Directory for scripts run daily by cron." },
            { "/etc/cron.hourly", "Directory for scripts run hourly by cron." },
            { "/etc/cron.monthly", "Directory for scripts run monthly by cron." },
            { "/etc/cron.weekly", "Directory for scripts run weekly by cron." },
            { "/etc/dhcp", "Configuration files for the DHCP client." },
            { "/etc/mysql", "Configuration files for MySQL." },
            { "/etc/nginx", "Configuration files for the Nginx web server." },
            { "/etc/apache2", "Configuration files for the Apache web server." },
            { "/etc/udev/rules.d", "Custom udev rules." },
            { "/etc/samba/smb.conf", "Configuration file for Samba server." },
            { "/etc/sysconfig/network-scripts", "Scripts for network interface configuration on some systems." },
            { "/etc/NetworkManager", "Configuration files for NetworkManager." },
            { "/etc/ssh/ssh_config", "Client-side configuration for SSH." },
            { "/etc/default/grub", "Configuration for GRUB bootloader." },
            { "/etc/acpi", "Actions and events for ACPI (Advanced Configuration and Power Interface)." },
            { "/etc/alternatives", "Symbolic links for choosing default commands." },
            { "/etc/anacrontab", "Schedule of periodic background jobs not necessarily run at specific times." },
            { "/etc/asound.conf", "Configuration for ALSA sound system." },
            { "/etc/audit", "Configuration files for the Linux Audit framework." },
            { "/etc/bind", "Configuration files for BIND DNS server." },
            { "/etc/binfmt.d", "Configuration for the kernel's binary format handlers." },
            { "/etc/blkid", "Block device attributes." },
            { "/etc/brltty", "Configuration for Braille display." },
            { "/etc/chkconfig.d", "Scripts for the chkconfig command." },
            { "/etc/cron.allow", "List of users allowed to use cron." },
            { "/etc/cron.deny", "List of users denied access to cron." },
            { "/etc/crypttab", "Crypto devices setup during boot." },
            { "/etc/default/useradd", "Default values for new user accounts." },
            { "/etc/depmod.d", "Configuration for module dependency listings." },
            { "/etc/dhcp/dhclient.conf", "Client configuration for DHCP." },
            { "/etc/dracut.conf", "Configuration for the Dracut initramfs generator." },
            { "/etc/fail2ban", "Configuration for Fail2Ban, a log-parsing application which bans IP addresses making too many password failures." },
            { "/etc/fonts", "Font configuration files." },
            { "/etc/fuse.conf", "Configuration file for Filesystem in Userspace (FUSE)." },
            { "/etc/gdm3", "Configuration files for GNOME Display Manager (GDM)." },
            { "/etc/ghostscript", "Configuration for Ghostscript (interpreter for PostScript and PDF)." },
            { "/etc/grub.d", "Scripts for generating GRUB2 configurations." },
            { "/etc/hdparm.conf", "Configuration for hard drive parameters." },
            { "/etc/hostname.conf", "Configuration for host name resolution." },
            { "/etc/init", "Upstart init system configuration scripts (for systems using Upstart)." },
            { "/etc/iproute2", "Configuration for IP routing utilities." },
            { "/etc/iptables", "Configuration files for iptables firewall." },
            { "/etc/krb5.conf", "Kerberos network authentication protocol configuration." },
            { "/etc/ld.so.cache", "Cache file for the dynamic linker." },
            { "/etc/libaudit.conf", "Configuration for the audit library." },
            { "/etc/login.defs", "Shadow password suite configuration." },
            { "/etc/lvm", "Configuration for Logical Volume Manager." },
            { "/etc/magic", "File type definitions for file command." },
            { "/etc/mailcap", "MIME types and applications handling them." },
            { "/etc/mke2fs.conf", "Configuration file for the mke2fs utility (used to create ext2/ext3/ext4 filesystems)." },
            { "/etc/modules-load.d", "Kernel modules to load at boot time." },
            { "/etc/mtab", "Currently mounted filesystems (often a symlink to /proc/mounts)." },
            { "/etc/mtools.conf", "Configuration file for mtools, utilities to access MS-DOS disks." },
            { "/etc/nanorc", "Global configuration for the nano text editor." },
            { "/etc/network/interfaces", "Network interface configuration for systems using ifup and ifdown." },
            { "/etc/nscd.conf", "Name Service Cache Daemon configuration." },
            { "/etc/openldap", "Configuration files for OpenLDAP." },
            { "/etc/opt", "Configuration files for add-on application software packages." },
            { "/etc/pam.conf", "Deprecated PAM configuration file, superseded by /etc/pam.d." },
            { "/etc/pki", "Public Key Infrastructure data." },
            { "/etc/pm", "Power management configuration." },
            { "/etc/polkit-1", "PolicyKit configuration files." },
            { "/etc/ppp", "Configuration files for Point-to-Point Protocol (PPP)." },
            { "/etc/profile.csh", "System-wide initialization script for C shell sessions." },
            { "/etc/python", "Python-related configurations." },
            { "/etc/rc.keymap", "Keyboard mapping script for console." },
            { "/etc/rpm", "Configuration files for RPM Package Manager." },
            { "/etc/rsnapshot.conf", "Configuration for rsnapshot, a filesystem snapshot utility." },
            { "/etc/selinux", "Configuration files for SELinux (Security-Enhanced Linux)." },
            { "/etc/sensors.d", "Configuration for hardware monitoring sensors." },
            { "/etc/smartd.conf", "Configuration file for smartd, the SMART Disk Monitoring Daemon." },
            { "/etc/snmp", "Configuration for SNMP (Simple Network Management Protocol)." },
            { "/etc/ssh/ssh_known_hosts", "Pre-known SSH hosts for client-side SSH." },
            { "/etc/ssl/openssl.cnf", "Configuration for OpenSSL." },
            { "/etc/sysconfig/firewall", "Firewall configuration on some systems." },
            { "/etc/system-release", "Contains the release version of the installed system." },
            { "/etc/tmpfiles.d", "Configuration for temporary files and directories." },
            { "/etc/ufw", "Configuration files for Uncomplicated Firewall (UFW)." },
            { "/etc/vconsole.conf", "Configuration for the virtual console." },
            { "/etc/vim/vimrc", "System-wide configuration file for Vim editor." },
            { "/etc/vsftpd", "Configuration files for vsftpd FTP server." },
            { "/etc/wgetrc", "Global configuration for wget, the non-interactive network downloader." },
            { "/etc/X11/xorg.conf", "Configuration file for the X.Org X server." },
            { "/etc/xdg", "Base directory specification configuration." },
            { "/etc/xml", "Configuration files for XML." },
            { "/etc/yum.repos.d", "Repository configuration for YUM." },
            { "/etc/zypp", "Configuration files for Zypper package manager." },
            { "/etc/security/limits.conf", "Configuration for setting user limits." },
            { "/etc/DIR_COLORS", "Defines color settings for ls command output." },
            { "/etc/magic.mime", "MIME type definitions for the file command." },
            { "/etc/mail.rc", "Configuration file for mail command." },
            { "/etc/network/if-up.d", "Scripts run after network interfaces go up." },
            { "/etc/network/if-down.d", "Scripts run after network interfaces go down." },
            { "/etc/network/if-pre-up.d", "Scripts run before network interfaces go up." },
            { "/etc/network/if-post-down.d", "Scripts run after network interfaces go down." },
            { "/etc/papersize", "Default paper size for print applications." },
            { "/etc/profile.local", "Local system-wide shell initialization script." },
            { "/etc/rcS.d", "Scripts for the start of the S runlevel." },
            { "/etc/ssh/ssh_host_key", "Host key for SSH (generic)." },
            { "/etc/ssh/ssh_host_rsa_key", "Host key for SSH (RSA)." },
            { "/etc/ssh/ssh_host_dsa_key", "Host key for SSH (DSA)." },
            { "/etc/ssh/ssh_host_ecdsa_key", "Host key for SSH (ECDSA)." },
            { "/etc/ssh/ssh_host_ed25519_key", "Host key for SSH (Ed25519)." },
            { "/etc/sysconfig/clock", "Contains timezone and UTC settings." },
            { "/etc/terminfo", "Database of terminal information." },
            { "/etc/update-motd.d", "Scripts for dynamic Message of the Day updates." },
            { "/etc/vim/vimrc.local", "Local system-wide configuration for Vim." },
            { "/etc/wpa_supplicant/wpa_supplicant.conf", "Configuration for WPA Supplicant for Wi-Fi networks." },
            { "/etc/dpkg", "Configuration files and scripts for the dpkg package management system." },
            { "/etc/python3.8", "Configuration files specific to Python 3.8." },
            { "/etc/pulse", "Configuration files for PulseAudio, a sound server." },
            { "/etc/vulkan", "Configuration files related to Vulkan, a graphics and compute API." },
            { "/etc/rc2.d", "Scripts that are run at runlevel 2." },
            { "/etc/rc3.d", "Scripts that are run at runlevel 3." },
            { "/etc/rc4.d", "Scripts that are run at runlevel 4." },
            { "/etc/rc5.d", "Scripts that are run at runlevel 5." },
            { "/etc/cloud", "Configuration files for cloud-init." },
            { "/etc/sysctl.d", "Configuration files for sysctl, for modifying kernel parameters." },
            { "/etc/ssh", "Configuration files for the Secure Shell (SSH) protocol." },
            { "/etc/console-setup", "Configuration files related to the setup of the console." },
            { "/etc/fwupd", "Configuration files for fwupd, a device firmware update daemon." },
            { "/etc/PackageKit", "Configuration files for PackageKit, a package management system." },
            { "/etc/update-manager", "Configuration files for the Update Manager." },
            { "/etc/rc0.d", "Scripts for the shutdown runlevel 0." },
            { "/etc/rc1.d", "Scripts for runlevel 1, single-user mode." },
            { "/etc/rc6.d", "Scripts for the reboot runlevel 6." },
            { "/etc/pollinate", "Scripts or configuration for the Pollinate service." },
            { "/etc/bash_completion.d", "Scripts for bash shell auto-completion." },
            { "/etc/logrotate.d", "Configuration files for logrotate." },
            { "/etc/apport", "Configuration files for Apport, a crash reporting system." },
            { "/etc/sudoers.d", "Additional configuration for the sudo system." },
            { "/etc/apparmor.d", "Profiles for AppArmor, a security module." },
            { "/etc/cryptsetup-initramfs", "Configuration for cryptsetup in initramfs." },
            { "/etc/rsyslog.d", "Configuration files for rsyslog." },
            { "/etc/initramfs-tools", "Tools and scripts for creating initramfs." },
            { "/etc/groff", "Configuration files for Groff, a typesetting system." },
            { "/etc/vmware-tools", "Configuration files for VMware Tools." },
            { "/etc/iscsi", "Configuration files for iSCSI protocol." },
            { "/etc/byobu", "Configuration files for Byobu, a text-based window manager." },
            { "/etc/mdadm", "Configuration files for mdadm, a tool for managing MD devices." },
            { "/etc/calendar", "Configuration files for the calendar command." },
            { "/etc/apparmor", "General configuration files for AppArmor." },
            { "/etc/logcheck", "Configuration files for logcheck." },
            { "/etc/network", "Scripts and configurations for network interfaces." },
            { "/etc/dconf", "Configuration files for dconf." },
            { "/etc/kernel", "Scripts and configurations related to the Linux kernel." },
            { "/etc/gss", "Configuration files related to GSS-API." },
            { "/etc/perl", "Configuration files for Perl." },
            { "/etc/ubuntu-advantage", "Configuration for Ubuntu Advantage." },
            { "/etc/python3", "Configuration files for Python 3." },
            { "/etc/vim", "Configuration files for Vim, a text editor." },
            { "/etc/newt", "Configuration files for Newt." },
            { "/etc/ssl", "Configuration files and certificates for SSL/TLS." },
            { "/etc/networkd-dispatcher", "Scripts run by networkd-dispatcher." },
            { "/etc/dbus-1", "Configuration files for D-Bus." },
            { "/etc/ca-certificates", "Certificates and related configuration." },
            { "/etc/apt", "Configuration files for APT, a package management tool." },
            { "/etc/landscape", "Configuration files for Landscape management tool." },
            { "/etc/netplan", "Configuration files for Netplan, a network configuration tool." },
            { "/etc/update-notifier", "Configuration files for the update notifier." }
        };
    }
}